### ISSUE TITLE
pyLODE not working

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#159] opened 2020-05-16 17:49 UTC
In a couple of tests, I couldn't get pyLODE to work on mmisw.org/ont. It just says Internal Error.

For example see image.
<img width="935" alt="Screen Shot 2020-05-16 at 10 42 16 AM" src="https://user-images.githubusercontent.com/1266896/82126660-e56df800-9762-11ea-885e-befcae5670cd.png">

**Comment by carueda** [comment] 2020-05-17 21:53
Dependent on https://github.com/RDFLib/pyLODE/issues/72

**Comment by carueda** [comment] 2020-05-18 17:22
Also, please note that this is not a bug in the orr-portal software: the configuration of any so-called "external viewers" is optional and up to the particular ORR deployment. In this case, however, as there's no some proper MMI ORR tracker (where it would be more appropriate to capture), let's just (continue to) use this tracker as the de facto one.  As part of this I'm removing @lewismc as assignee.

**Comment by lewismc** [comment] 2020-05-18 17:40
+1

**Comment by lewismc** [comment] 2020-05-26 22:28
The issues should have been fixed in pyLODE. Can you upgrade and verify @graybeal ?

**Comment by graybeal** [comment] 2020-05-26 23:48
@carueda I think I'll forward this request to update pyLODE to you, if you have time. I'm happy to test once done.

**Comment by carueda** [comment] 2020-05-27 00:04
@graybeal  Ok, just pulled pyLODE's master and restarted the service.  A quick test OK with CF:

![image](https://user-images.githubusercontent.com/556505/82961583-a1ed6800-9f72-11ea-9d9b-8a69b6d8be8a.png)

Thanks @lewismc for confirming the fixes on the pyLODE side.

**Closed by carueda** 2020-05-27 00:04 UTC
