### ISSUE TITLE
mappings didn't work

### ISSUE THREAD

**Issue by graybeal** [mmisw/orr-portal#52] opened 2016-07-05 06:17 UTC
I selected a few ontologies and tried to map a few terms, but couldn't see that anything was happening. I might have gotten one mapping to work, but that was it.

Also wasn't clear what the 2nd row from the bottom of the page was, that looked like 3 empty fields to fill in. Could be useful I'm guessing, but I'm not sure how.

**Comment by carueda** [comment] 2016-07-07 05:22
I'm not really aware of any significant issues with the mapping tool.  Please provide more details when you get a chance.

**Comment by carueda** [comment] 2016-07-13 05:07
Ah! forgot about this, and since it was not marked bug, I missed to notice it;  anyway simply closing as duplicate of #56

**Closed by carueda** 2016-07-13 05:07 UTC
Labels: duplicate, m2r
