### ISSUE TITLE
Unable to upload file to create new version of existing ontology

### ISSUE THREAD

**Issue by lewismc** [mmisw/orr-portal#100] opened 2017-04-12 03:09 UTC
The issue is that I am unable to upload a new file/version of a resource, the **Upload file** button seems to not work.
<img width="1440" alt="screen shot 2017-04-11 at 8 08 24 pm" src="https://cloud.githubusercontent.com/assets/1165719/24939513/b9c6d1e0-1ef2-11e7-8ff7-0977dc330054.png">

**Comment by carueda** [comment] 2017-04-12 03:31
This is very likely caused by the issue exposed by the box with the red border color in the background of your screenshot, which is what I captured in #99 .  Once that one is resolved the Upload button should work.  So, let me work on #99 first.

**Comment by lewismc** [comment] 2017-04-12 03:32
ack

**Comment by carueda** [comment] 2017-04-12 04:04
Closing this one as well per #98 and #99.

**Closed by carueda** 2017-04-12 04:04 UTC
Labels: bug, Priority-High
